import "@/assets/stylesheets/app.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Newsletter App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="antialiased">{children}</body>
        </html>
    );
}
