import "@/assets/stylesheets/app.css";
import Sidenav from "@/partials/Sidenav";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Newsletter App",
    description: "Generated by create next app",
};

export default async function Layout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="h-screen flex">
            <Sidenav />

            <main className="bg-gray-50 dark:bg-gray-900 h-screen overflow-y w-full">
                {children}
            </main>
        </div>
    );
}
